// Generated by gencpp from file scada_project/Service.msg
// DO NOT EDIT!


#ifndef SCADA_PROJECT_MESSAGE_SERVICE_H
#define SCADA_PROJECT_MESSAGE_SERVICE_H

#include <ros/service_traits.h>


#include <scada_project/ServiceRequest.h>
#include <scada_project/ServiceResponse.h>


namespace scada_project
{

struct Service
{

typedef ServiceRequest Request;
typedef ServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Service
} // namespace scada_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scada_project::Service > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::scada_project::Service&) { return value(); }
};

template<>
struct DataType< ::scada_project::Service > {
  static const char* value()
  {
    return "scada_project/Service";
  }

  static const char* value(const ::scada_project::Service&) { return value(); }
};


// service_traits::MD5Sum< ::scada_project::ServiceRequest> should match 
// service_traits::MD5Sum< ::scada_project::Service > 
template<>
struct MD5Sum< ::scada_project::ServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scada_project::Service >::value();
  }
  static const char* value(const ::scada_project::ServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scada_project::ServiceRequest> should match 
// service_traits::DataType< ::scada_project::Service > 
template<>
struct DataType< ::scada_project::ServiceRequest>
{
  static const char* value()
  {
    return DataType< ::scada_project::Service >::value();
  }
  static const char* value(const ::scada_project::ServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scada_project::ServiceResponse> should match 
// service_traits::MD5Sum< ::scada_project::Service > 
template<>
struct MD5Sum< ::scada_project::ServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scada_project::Service >::value();
  }
  static const char* value(const ::scada_project::ServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scada_project::ServiceResponse> should match 
// service_traits::DataType< ::scada_project::Service > 
template<>
struct DataType< ::scada_project::ServiceResponse>
{
  static const char* value()
  {
    return DataType< ::scada_project::Service >::value();
  }
  static const char* value(const ::scada_project::ServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCADA_PROJECT_MESSAGE_SERVICE_H
