// Generated by gencpp from file elaboratoR1/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ELABORATOR1_MESSAGE_ADDTWOINTS_H
#define ELABORATOR1_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <elaboratoR1/AddTwoIntsRequest.h>
#include <elaboratoR1/AddTwoIntsResponse.h>


namespace elaboratoR1
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace elaboratoR1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::elaboratoR1::AddTwoInts > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::elaboratoR1::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::elaboratoR1::AddTwoInts > {
  static const char* value()
  {
    return "elaboratoR1/AddTwoInts";
  }

  static const char* value(const ::elaboratoR1::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::elaboratoR1::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::elaboratoR1::AddTwoInts > 
template<>
struct MD5Sum< ::elaboratoR1::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::elaboratoR1::AddTwoInts >::value();
  }
  static const char* value(const ::elaboratoR1::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::elaboratoR1::AddTwoIntsRequest> should match 
// service_traits::DataType< ::elaboratoR1::AddTwoInts > 
template<>
struct DataType< ::elaboratoR1::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::elaboratoR1::AddTwoInts >::value();
  }
  static const char* value(const ::elaboratoR1::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::elaboratoR1::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::elaboratoR1::AddTwoInts > 
template<>
struct MD5Sum< ::elaboratoR1::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::elaboratoR1::AddTwoInts >::value();
  }
  static const char* value(const ::elaboratoR1::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::elaboratoR1::AddTwoIntsResponse> should match 
// service_traits::DataType< ::elaboratoR1::AddTwoInts > 
template<>
struct DataType< ::elaboratoR1::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::elaboratoR1::AddTwoInts >::value();
  }
  static const char* value(const ::elaboratoR1::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ELABORATOR1_MESSAGE_ADDTWOINTS_H
