// Generated by gencpp from file elaboratoR1_B/Message1.msg
// DO NOT EDIT!


#ifndef ELABORATOR1_B_MESSAGE_MESSAGE1_H
#define ELABORATOR1_B_MESSAGE_MESSAGE1_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace elaboratoR1_B
{
template <class ContainerAllocator>
struct Message1_
{
  typedef Message1_<ContainerAllocator> Type;

  Message1_()
    {
    }
  Message1_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::elaboratoR1_B::Message1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::elaboratoR1_B::Message1_<ContainerAllocator> const> ConstPtr;

}; // struct Message1_

typedef ::elaboratoR1_B::Message1_<std::allocator<void> > Message1;

typedef boost::shared_ptr< ::elaboratoR1_B::Message1 > Message1Ptr;
typedef boost::shared_ptr< ::elaboratoR1_B::Message1 const> Message1ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::elaboratoR1_B::Message1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::elaboratoR1_B::Message1_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace elaboratoR1_B

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'elaboratoR1_B': ['/home/leo/elaborato1/src/elaboratoR1_B/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::elaboratoR1_B::Message1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::elaboratoR1_B::Message1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::elaboratoR1_B::Message1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::elaboratoR1_B::Message1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::elaboratoR1_B::Message1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::elaboratoR1_B::Message1_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::elaboratoR1_B::Message1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::elaboratoR1_B::Message1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::elaboratoR1_B::Message1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "elaboratoR1_B/Message1";
  }

  static const char* value(const ::elaboratoR1_B::Message1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::elaboratoR1_B::Message1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::elaboratoR1_B::Message1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::elaboratoR1_B::Message1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Message1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::elaboratoR1_B::Message1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::elaboratoR1_B::Message1_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ELABORATOR1_B_MESSAGE_MESSAGE1_H
